my_list= list(map(int,input("Enter The Elemets Two the List Sepate it by space").split()))

minimum = min(my_list)
print("Minimum value:", minimum)
maximum = max(my_list)
print("Maximum value:", maximum)
count=len(my_list)
print("Count of list:", count)
total = sum(my_list)
print("Total sum:", total)
my_list.sort()
print("Sorted list:", my_list)
my_list.reverse()
print("Reversed list:", my_list)
